### ISSUE TITLE
nil pointer dereference with param in BasePath

### ISSUE THREAD

**Issue by smessier** [goadesign/goa#1154]
I see a nil pointer dereference with goagen v1 when the design has a resource with a parameter in the BasePath. If I remove the parameter then the crash goes away.

$GOPATH/src/foo/design/design.go
```
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("widget_service", func() {
	BasePath("/widget_service")
})

var _ = Resource("widget", func() {
	BasePath("/v1/projects/:projectID/widgets")  // note that if you remove :projectID then the crash goes away
	DefaultMedia(WidgetMedia)
	Action("show", func() {
		Routing(GET("/:sha"))
		Params(func() {
			Param("projectID", String, "Project ID")
			Param("sha", String, "SHA")
			Required("projectID", "sha")
		})
		Response(OK)
		Response(NotFound)
	})
})

var WidgetMedia = MediaType("application/vnd.widgetsrus.widget", func() {
	Attributes(func() {
		Attribute("id", String, "Identifier")
	})
	View("default", func() {
		Attribute("id")
	})
	Required("id")
})
```
If you run the latest goagen with this design you see the crash:
```
~/gopath/src/foo$ goagen app --design foo/design
exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6ee67f]

goroutine 1 [running]:
github.com/goadesign/goa/design.(*ResourceDefinition).PathParams(0xc4201e2000, 0xc4201e6200)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:685 +0xdf
github.com/goadesign/goa/design.(*ActionDefinition).AllParams(0xc4201d2280, 0x1)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:1386 +0x3b4
github.com/goadesign/goa/design.(*ActionDefinition).initQueryParams(0xc4201d2280)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:1603 +0x43
github.com/goadesign/goa/design.(*ActionDefinition).Finalize(0xc4201d2280)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:1475 +0x98
github.com/goadesign/goa/design.(*ResourceDefinition).Finalize.func2(0xc4201d2280, 0xc4201d03f0, 0x83e4a1)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:871 +0x3d
github.com/goadesign/goa/design.(*ResourceDefinition).IterateActions(0xc4201e2000, 0xc42020bc90, 0x0, 0x0)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:702 +0x1d2
github.com/goadesign/goa/design.(*ResourceDefinition).Finalize(0xc4201e2000)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:873 +0x138
github.com/goadesign/goa/dslengine.finalizeSet(0xc420177930, 0x1, 0x1, 0x0, 0x1)
	~/gopath/src/github.com/goadesign/goa/dslengine/runner.go:330 +0x8e
github.com/goadesign/goa/design.(*APIDefinition).IterateSets(0xc42017e420, 0x870158)
	~/gopath/src/github.com/goadesign/goa/design/definitions.go:498 +0x569
github.com/goadesign/goa/dslengine.Run(0xa49480, 0xc42018ace0)
	~/gopath/src/github.com/goadesign/goa/dslengine/runner.go:114 +0x20b
main.main()
	~/gopath/src/foo/goagen176070381/main.go:25 +0x5a
```
If I revert the goa repo to the commit before 3/28/2017 then the crash goes away:
```
~/gopath/src/foo$ goagen app --design foo/design
app
app/contexts.go
app/controllers.go
app/hrefs.go
app/media_types.go
app/user_types.go
app/test
app/test/widget_testing.go
```

**Comment by raphael** [comment]
Thanks for the detailed report. Is there a reason for the resource path parameter to be defined in the action instead of the resource? this works fine:
```go
var _ = Resource("widget", func() {
	BasePath("/v1/projects/:projectID/widgets")  // note that if you remove :projectID then the crash goes away
        Param("projectID", String, "Project ID")
	DefaultMedia(WidgetMedia)
	Action("show", func() {
		Routing(GET("/:sha"))
		Params(func() {
			Param("sha", String, "SHA")
			Required("projectID", "sha")
		})
		Response(OK)
		Response(NotFound)
	})
})
```
I have a fix that validates that resources that use parameters in their base paths define them but want to make sure there's no valid use case for defining it in the action.

**Comment by raphael** [comment]
After thinking more about this it seems better to keep  the previous behavior where parameters do not have to be defined at the resource level. The semantic is that path parameters default to `String` attributes if not defined. Resource path parameters can be defined at the action level and if not follow the same default.

**Comment by smessier** [comment]
Yes, it is probably better to change the design to define the parameters at the base instead of each resource. The crash was due to legacy behavior and was therefore unexpected.
