### ISSUE TITLE
notool flag does not work with bootstrap command

### ISSUE THREAD

**Issue by azihsoyn** [goadesign/goa#1467]
It's looks like same cause with #769

```
goagen bootstrap -d github.com/goa-cellar/design --notool
exit status 2
flag provided but not defined: -notool
Usage of app:
  -design string

  -force

  -notest

  -out string

  -pkg string
    	 (default "app")
  -regen

  -tooldir string
    	 (default "tool")
  -version string

panic: flag provided but not defined: -notool

goroutine 1 [running]:
flag.(*FlagSet).Parse(0xc4201095c0, 0xc42008e100, 0x4, 0x4, 0x0, 0x0)
	/Users/naoya/.gobrew/versions/1.9/src/flag/flag.go:926 +0x116
github.com/goadesign/goa/goagen/gen_app.Generate(0x0, 0x0, 0x1698740, 0x16f36e0, 0xc420076058)
	/Users/naoya/.go/src/github.com/goadesign/goa/goagen/gen_app/generator.go:53 +0x3a4
main.main()
	/Users/naoya/.go/src/github.com/goa-cellar/goagen340317514/main.go:27 +0x64
```

Thanks.

**Comment by azihsoyn** [comment]
using version is 1.3.0
```
$ goagen version
goagen v1.3.0
The goa generation tool.
```

**Comment by raphael** [comment]
Thank you for the report, this is now fixed.
