### ISSUE TITLE
V2 Temporary() causes nil pointer when generating

### ISSUE THREAD

**Issue by dotLou** [goadesign/goa#1632]
## Expected Behavior
Error handler gets created, code is generated
## Actual Behavior
The following stack trace appears:

```
exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1171fda]

goroutine 1 [running]:
goa.design/goa/design.(*dupper).DupType(0xc4202797d0, 0x0, 0x0, 0x17e3220, 0x0)
        /Users/bih/dev/golang/src/goa.design/goa/design/dup.go:89 +0x65a
goa.design/goa/design.(*dupper).DupAttribute(0xc4202797d0, 0xc420302460, 0x14a9662)
        /Users/bih/dev/golang/src/goa.design/goa/design/dup.go:43 +0xcb
goa.design/goa/design.(*dupper).DupType(0xc4202797d0, 0x154e6c0, 0xc4202d46c0, 0x17e3220, 0xc420279700)
        /Users/bih/dev/golang/src/goa.design/goa/design/dup.go:85 +0x341
goa.design/goa/design.(*dupper).DupAttribute(0xc4202797d0, 0xc4203026e0, 0x20)
        /Users/bih/dev/golang/src/goa.design/goa/design/dup.go:43 +0xcb
goa.design/goa/design.DupAtt(0xc4203026e0, 0x154e6c0)
        /Users/bih/dev/golang/src/goa.design/goa/design/dup.go:16 +0xf5
goa.design/goa/http/design.ErrorResponseBody(0xc420312000, 0xc4202d44e0, 0xc4203026e0)
        /Users/bih/dev/golang/src/goa.design/goa/http/design/body_types.go:197 +0xa4f
goa.design/goa/http/design.(*ErrorExpr).Finalize(0xc4202d44e0, 0xc420312000)
        /Users/bih/dev/golang/src/goa.design/goa/http/design/error.go:62 +0x1be
goa.design/goa/http/design.(*EndpointExpr).Finalize(0xc420312000)
        /Users/bih/dev/golang/src/goa.design/goa/http/design/endpoint.go:607 +0xacd
goa.design/goa/eval.finalizeSet(0xc4202ca710, 0x1, 0x1, 0x0, 0x0)
        /Users/bih/dev/golang/src/goa.design/goa/eval/eval.go:104 +0x99
goa.design/goa/http/design.(*RootExpr).WalkSets(0x17c5000, 0x15106f8)
        /Users/bih/dev/golang/src/goa.design/goa/http/design/root.go:187 +0x48d
goa.design/goa/eval.RunDSL(0x7ffeefbfefd3, 0xc4202d60a6)
        /Users/bih/dev/golang/src/goa.design/goa/eval/eval.go:49 +0x221
main.main()
        /Users/bih/dev/golang/src/things/goa227818191/main.go:47 +0x235
```

## Steps to Reproduce the Problem (including complete and simple design if relevant)

`design.go`:
```go
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

// API describes the global properties of the API server.
var _ = API("things", func() {
	HTTP(func() {
		Consumes("application/json")
		Produces("application/json")
	})
})

// ThingPayload is the payload to be used to extend PayloadB
var ThingPayload = Type("ThingPayload", func() {
	Attribute("id", String)
})

var _ = Service("things", func() {
	Method("find", func() {
		Payload(ThingPayload)
		Result(Int)
		Error("not_found", func() {
			Temporary()
		})
		HTTP(func() {
			GET("/things/{id}")
			Response(StatusOK)
			Response("not_found", StatusNotFound)
		})
	})
})

var _ = Service("openapi", func() {
	Files("/openapi", "../../gen/http/openapi.json")
})
```
`goa gen things/design`

## Specifications

  - goa Version: latest v2, after merge of #1620 
  - Platform (Linux/Windows etc.): Mac OS X High Sierra

**Comment by raphael** [comment]
Thank you, this is now fixed.
