### ISSUE TITLE
ResultType causes an error on GRPC request

### ISSUE THREAD

**Issue by aya-eiya** [goadesign/goa#1989]
I tried to test the gRPC service which returns the result of Object type and tried using ResultType, but an error occurred at the time of request and the server stopped.

I do not know if I am mistaken or a bug in V2.

Here is a sample so I want you to see it for a while and tell me if you know something.

https://github.com/aya-eiya/goa-issue/tree/objectResult

thank you.

## Expected Behavior

```
{
  "result": "1 + 2 = 3"
}
```

## Actual Behavior

server side message
```
[calc] 14:55:37  id=Mw3fBA3f method=/pb.Calc/Add
panic: assignment to entry in nil map

goroutine 51 [running]:
google.golang.org/grpc/metadata.MD.Append(0x0, 0x14b5949, 0x8, 0xc0000df6e8, 0x1, 0x1)
        /Users/h_ayabe/Projects/Go/src/google.golang.org/grpc/metadata/metadata.go:120 +0x67
github.com/aya-eiya/goa-issue/gen/grpc/calc/server.EncodeAddResponse(0x152e2c0, 0xc0001d62d0, 0x13efc60, 0xc0001c4240, 0xc0001c8028, 0xc0001c8030, 0x0, 0x0, 0x0, 0xc0000c2300)
        /Users/h_ayabe/Projects/Go/src/github.com/aya-eiya/goa-issue/gen/grpc/calc/server/encode_decode.go:27 +0xae
goa.design/goa/grpc.(*unaryHandler).Handle(0xc0000b0700, 0x152e2c0, 0xc0001d62d0, 0x1484aa0, 0xc0001d6240, 0x143a060, 0x1429a00, 0x0, 0x15296e0)
        /Users/h_ayabe/Projects/Go/src/goa.design/goa/grpc/handler.go:96 +0x40f
github.com/aya-eiya/goa-issue/gen/grpc/calc/server.(*Server).Add(0xc000099860, 0x152e2c0, 0xc0001d62d0, 0xc0001d6240, 0xc000099860, 0x2, 0xb)
        /Users/h_ayabe/Projects/Go/src/github.com/aya-eiya/goa-issue/gen/grpc/calc/server/server.go:48 +0x61
github.com/aya-eiya/goa-issue/gen/grpc/calc/pb._Calc_Add_Handler.func1(0x152e2c0, 0xc0001d62d0, 0x1484aa0, 0xc0001d6240, 0x10053a10000d762b, 0xc0000df8e0, 0xc0001c4220, 0xc0001ec2a0)
        /Users/h_ayabe/Projects/Go/src/github.com/aya-eiya/goa-issue/gen/grpc/calc/pb/calc.pb.go:189 +0x86
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x152e2c0, 0xc0001d62d0, 0x1484aa0, 0xc0001d6240, 0xc0001ca0d0, 0xc00009c5a0, 0xc0001c0120, 0xc0000df9c8)
        /Users/h_ayabe/Projects/Go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x118
goa.design/goa/grpc/middleware.Log.func1(0x152e2c0, 0xc0001d62d0, 0x1484aa0, 0xc0001d6240, 0xc0001c41e0, 0xc0001c6410, 0x10cc7cb, 0x147a140, 0xc0001d62d0, 0x1406b40)
        /Users/h_ayabe/Projects/Go/src/goa.design/goa/grpc/middleware/log.go:52 +0x1e3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x152e2c0, 0xc0001d62d0, 0x1484aa0, 0xc0001d6240, 0x1407b40, 0xc0001ca0d0, 0x152e2c0, 0xc0001d62d0)
        /Users/h_ayabe/Projects/Go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9f
goa.design/goa/grpc/middleware.RequestID.func1(0x152e2c0, 0xc0001d6210, 0x1484aa0, 0xc0001d6240, 0xc0001c41e0, 0xc0001c6410, 0xc0001d1af8, 0x100dba8, 0xc0000dfb08, 0x100dba8)
        /Users/h_ayabe/Projects/Go/src/goa.design/goa/grpc/middleware/requestid.go:14 +0xcb
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x152e2c0, 0xc0001d6210, 0x1484aa0, 0xc0001d6240, 0xc0001c41e0, 0xc0001c4200, 0x1432c00, 0x1851e50, 0x149fa00, 0xc0001e8000)
        /Users/h_ayabe/Projects/Go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x153
github.com/aya-eiya/goa-issue/gen/grpc/calc/pb._Calc_Add_Handler(0x1429a00, 0xc000099860, 0x152e2c0, 0xc0001d6210, 0xc0001c6230, 0xc00009de00, 0x0, 0x0, 0xc0001c00e8, 0x4)
        /Users/h_ayabe/Projects/Go/src/github.com/aya-eiya/goa-issue/gen/grpc/calc/pb/calc.pb.go:191 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008c780, 0x152ff80, 0xc00008cf00, 0xc0001e8000, 0xc00009df20, 0x1824d90, 0x0, 0x0, 0x0)
        /Users/h_ayabe/Projects/Go/src/google.golang.org/grpc/server.go:966 +0x4a2
google.golang.org/grpc.(*Server).handleStream(0xc00008c780, 0x152ff80, 0xc00008cf00, 0xc0001e8000, 0x0)
        /Users/h_ayabe/Projects/Go/src/google.golang.org/grpc/server.go:1245 +0xd61
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000a2b94, 0xc00008c780, 0x152ff80, 0xc00008cf00, 0xc0001e8000)
        /Users/h_ayabe/Projects/Go/src/google.golang.org/grpc/server.go:685 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/h_ayabe/Projects/Go/src/google.golang.org/grpc/server.go:683 +0xa1
```

client side message
```
Error:  { Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/Users/h_ayabe/.nvm/versions/node/v7.10.0/lib/node_modules/grpcc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/h_ayabe/.nvm/versions/node/v7.10.0/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/h_ayabe/.nvm/versions/node/v7.10.0/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/h_ayabe/.nvm/versions/node/v7.10.0/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/h_ayabe/.nvm/versions/node/v7.10.0/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:845:24) code: 2, metadata: {}, details: 'Stream removed' }
```

## Steps to Reproduce the Problem (including complete and simple design if relevant)

Here is the sample project.

https://github.com/aya-eiya/goa-issue/tree/objectResult

## Specifications

  - goa Version:goa version v2.0.0-wip
  - Platform (Linux/Windows etc.):MacOSX

**Comment by raphael** [comment]
Thank you for the detailed report! this looks like a bug.

**Comment by nitinmohan87** [comment]
@aya-eiya I am not able to reproduce this problem by copying your design. Are you sure you are using the latest goa v2?
```
// server
$ ./calc
[calc] 14:03:05 serving gRPC method pb.Calc/Add
[calc] 14:03:05 gRPC server listening on "localhost:8080"
[calc] 14:03:38  id=53cBfrqU method=/pb.Calc/Add bytes=4
[calc] 14:03:38  id=53cBfrqU status=OK bytes=11 time=90.385µs

// client
$ ./calc-cli --url="grpc://localhost:8080" calc add --message '{"a": 1, "b": 2 }'
{
    "Result": "1 + 2 = 3"
}
```

**Comment by aya-eiya** [comment]
@nitinmohan87 Thank you to check my code.

you are right, My goa was old.

 the problem was already fixed on latest v2 code.

Thank you.
