### ISSUE TITLE
goa gen panics if HTTP and GRPC are used together with CORS

### ISSUE THREAD

**Issue by rhotz** [goadesign/goa#2033]
I did face a bug when using HTTP and GRPC together with CORS.

## Expected Behavior
goa gen should generate the stubs.

## Actual Behavior
goa gen panics:

```
goa gen test/design
exit status 2
panic: interface conversion: interface {} is *codegen.ServiceData, not *codegen.ServiceData (types from different packages)

goroutine 1 [running]:
goa.design/plugins/cors.serverCORS(0xc0002ae5c0)
        /mnt/c/work/go/src/goa.design/plugins/cors/generate.go:83 +0x11df
goa.design/plugins/cors.Generate(0xc000246553, 0x8, 0xc000243380, 0x3, 0x4, 0xc00027ab00, 0x18, 0x2c, 0x442602, 0x414c3a, ...)
        /mnt/c/work/go/src/goa.design/plugins/cors/generate.go:42 +0x38
goa.design/goa/codegen.RunPlugins(0xa73abe, 0x3, 0xc000246553, 0x8, 0xc000243380, 0x3, 0x4, 0xc00027ab00, 0x18, 0x2c, ...)
        /mnt/c/work/go/src/goa.design/goa/codegen/plugin.go:119 +0x177
goa.design/goa/codegen/generator.Generate(0x7fffd1e8a1ee, 0x1, 0xa73abe, 0x3, 0x4, 0xc000240450, 0xa, 0xc00023aa20, 0x30)
        /mnt/c/work/go/src/goa.design/goa/codegen/generator/generate.go:70 +0x50e
main.main()
        /mnt/c/work/go/src/test/goa400051572/main.go:54 +0x47f
```

## Steps to Reproduce the Problem
Creating a simple design document with HTTP, GRPC and CORS makes goa gen panic:

Example test/design.go  (simplified)

```
package design

import (
    . "goa.design/goa/dsl"
    cors "goa.design/plugins/cors/dsl"
)

var _ = API("test", func() {

    cors.Origin("localhost")

    Server("test", func() {
        Services("test")
        Host("development", func() {
            URI("http://localhost:8000/test")
            URI("grpc://localhost:8080")
        })
    })
})

var _ = Service("test", func() {
    Method("test", func() {
        Result(Int)
        HTTP(func() {
            GET("/test")
            Response(StatusOK)
        })

        GRPC(func() {
            Response(CodeOK)
        })
    })
})
```

## Specifications
* goa.design/goa on branch v2
* goa.design/plugins on branch master

**Comment by nitinmohan87** [comment]
Thanks for the bug fix!
