### ISSUE TITLE
goa v2 panics when using unsupported Any type

### ISSUE THREAD

**Issue by smessier** [goadesign/goa#2034]
If you (improperly) use the Any type, as in the following example:
`$GOPATH/src/foo/design.go`
```package design

import (
	. "goa.design/goa/dsl"
)

var _ = Service("Something", func() {
	Method("create", func() {
		Payload(func() {
			Field(1, "name", String)
			Field(2, "bad", Any)
		})
		Result(Empty)

		GRPC(func() {
			Response(CodeOK)
		})
	})
})
```
then you get a panic without any error detail:
```$ goa gen foo/design
exit status 2
panic: cannot compute native protocol buffer type for expr.Primitive

goroutine 1 [running]:
goa.design/goa/grpc/codegen.protoBufNativeMessageTypeName(0xb301a0, 0xb232c8, 0xc0001790e8, 0x40d19f)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/protobuf.go:361 +0x2a9
goa.design/goa/grpc/codegen.protoBufMessageDef(0xc0002b6fa0, 0xc00019b2c0, 0xc0001b1746, 0x3)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/protobuf.go:239 +0x9d
goa.design/goa/grpc/codegen.protoBufMessageDef(0xc0002b6e60, 0xc00019b2c0, 0xc0001b0ad0, 0xd)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/protobuf.go:259 +0x2b1
goa.design/goa/grpc/codegen.collectMessages(0xc0002b6c80, 0xc000272ea0, 0xc0002c0270, 0x441fd1, 0xc0001ae398, 0x0)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/service_data.go:602 +0x7cb
goa.design/goa/grpc/codegen.ServicesData.analyze.func1(0xc0002b6c80, 0x0)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/service_data.go:431 +0x52
goa.design/goa/grpc/codegen.ServicesData.analyze(0xc000290330, 0xc0001957a0, 0x9)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/service_data.go:500 +0x2413
goa.design/goa/grpc/codegen.ServicesData.Get(0xc000290330, 0xa3ab51, 0x9, 0x40d19f)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/service_data.go:354 +0xb4
goa.design/goa/grpc/codegen.protoFile(0xc0001b819a, 0x7, 0xc0002b20c0, 0xc0001957a0, 0x1)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/proto.go:29 +0x62
goa.design/goa/grpc/codegen.ProtoFiles(0xc0001b819a, 0x7, 0xf09ba0, 0x0, 0x0, 0x0)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/proto.go:23 +0xef
goa.design/goa/codegen/generator.Transport(0xc0001b819a, 0x7, 0xc0001b4e20, 0x2, 0x2, 0x3, 0x4, 0x3, 0x0, 0x0)
	/home/me/gopath/src/goa.design/goa/codegen/generator/transport.go:33 +0x5fb
goa.design/goa/codegen/generator.Generate(0x7ffcb9ae09d8, 0x1, 0xa28988, 0x3, 0x0, 0x0, 0xc00019ace0, 0x0, 0xffffffffffffffff)
	/home/me/gopath/src/goa.design/goa/codegen/generator/generate.go:62 +0x362
main.main()
	/home/me/gopath/src/foo/goa893919833/main.go:54 +0x275
```
this is hard to debug when your design is complex so perhaps do not panic but instead say what type is unsupported and the line number.

**Comment by nitinmohan87** [comment]
Thanks for the bug report!
