### ISSUE TITLE
goa v2 grpc codegen panics when two methods return same collection

### ISSUE THREAD

**Issue by smessier** [goadesign/goa#2060]
The code generator panics if a service has two methods that have the same result type of collection. If one or the other is changed to return Empty or a non-collection then the panic goes away.

`$GOPATH/src/foo/design/api.go`
```
package design

import (
	. "goa.design/goa/dsl"
)

var _ = Service("Foo", func() {
	Method("a", func() {
		Result(CollectionOf(Bar))

		GRPC(func() {
			Response(CodeOK)
		})
	})

	Method("b", func() {
		Result(CollectionOf(Bar))

		GRPC(func() {
			Response(CodeOK)
		})
	})
})

var Bar = ResultType("application/vnd.foo.bar", func() {
	TypeName("Bar")
	Attributes(func() {
		Field(1, "name", String)
		Required("name")
	})
	View("default", func() {
		Attribute("name")
	})
})
```
Run the following:
```
~/gopath/src/foo$ goa gen foo/design
exit status 2
panic: runtime error: index out of range

goroutine 1 [running]:
goa.design/goa/grpc/codegen.ServicesData.analyze.func1(0xc00031fe00, 0xc00032d180)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/service_data.go:433 +0x1c2
goa.design/goa/grpc/codegen.ServicesData.analyze(0xc00026eb70, 0xc0002318c0, 0x3)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/service_data.go:527 +0x226f
goa.design/goa/grpc/codegen.ServicesData.Get(0xc00026eb70, 0xa1837b, 0x3, 0xc000236480)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/service_data.go:356 +0xb4
goa.design/goa/grpc/codegen.protoFile(0xc00024c28a, 0x7, 0xc0002318c0, 0xc0002344d8)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/proto.go:29 +0x62
goa.design/goa/grpc/codegen.ProtoFiles(0xc00024c28a, 0x7, 0xef2ba0, 0x0, 0x0, 0x0)
	/home/me/gopath/src/goa.design/goa/grpc/codegen/proto.go:23 +0xda
goa.design/goa/codegen/generator.Transport(0xc00024c28a, 0x7, 0xc000229340, 0x2, 0x2, 0x4, 0x4, 0x4, 0x0, 0x0)
	/home/me/gopath/src/goa.design/goa/codegen/generator/transport.go:33 +0x5fb
goa.design/goa/codegen/generator.Generate(0x7ffc4d644a08, 0x1, 0xa1876e, 0x3, 0x0, 0x0, 0xc000232d20, 0x0, 0xffffffffffffffff)
	/home/me/gopath/src/goa.design/goa/codegen/generator/generate.go:62 +0x362
main.main()
	/home/me/gopath/src/foo/goa236066888/main.go:54 +0x275
```

**Comment by nitinmohan87** [comment]
Thanks! This must be fixed now.
