### ISSUE TITLE
goa gen makes error with CollectionOf and Body

### ISSUE THREAD

**Issue by akm** [goadesign/goa#2062]
## Expected Behavior

`goa gen` generates an array instead of struct for `ListResponseBody` with DSL like https://github.com/akm/goa_v2_simple_example/blob/master/design/person.go#L36-L57

## Actual Behavior

```
$ goa gen github.com/akm/goa_v2_simple_example/design
exit status 2
res.People is an array but body type is
body is an object but v type is PersonCollection
panic: failed to project media type "application/vnd.person+json; type=collection": unknown view "default"

goroutine 1 [running]:
goa.design/goa/http/codegen/openapi.ResultTypeRefWithPrefix(0xc420162000, 0xc42026a180, 0x165618f, 0x7, 0x1651a64, 0x6, 0x0, 0xc420173278)
	$GOPATH/src/goa.design/goa/http/codegen/openapi/json_schema.go:230 +0x358
goa.design/goa/http/codegen/openapi.responseSpecFromExpr(0xc4203f2000, 0x19dafa0, 0xc4202624d0, 0x1651a64, 0x6, 0x0)
	$GOPATH/src/goa.design/goa/http/codegen/openapi/openapi_v2_builder.go:428 +0x4b2
goa.design/goa/http/codegen/openapi.buildPathFromExpr(0xc4203f2000, 0x19dafa0, 0xc42019bdb0, 0xc420266570, 0x0, 0x0)
	$GOPATH/src/goa.design/goa/http/codegen/openapi/openapi_v2_builder.go:555 +0x285
goa.design/goa/http/codegen/openapi.NewV2(0x19dafa0, 0xc42019bdb0, 0x3, 0xc4200170e0, 0x15)
	$GOPATH/src/goa.design/goa/http/codegen/openapi/openapi_v2_builder.go:91 +0xc0c
goa.design/goa/http/codegen.OpenAPIFiles(0x19dafa0, 0xe, 0x20, 0xc420157680, 0xc42024c850, 0x0)
	$GOPATH/src/goa.design/goa/http/codegen/openapi.go:27 +0x141
goa.design/goa/codegen/generator.OpenAPI(0xc42023c254, 0x28, 0xc42029c140, 0x2, 0x2, 0xa, 0x10, 0xa, 0x0, 0x0)
	$GOPATH/src/goa.design/goa/codegen/generator/openapi.go:16 +0x59
goa.design/goa/codegen/generator.Generate(0x7ffeefbff747, 0x1, 0x1648f67, 0x3, 0x1, 0x0, 0xc42018d300, 0x0, 0xffffffffffffffff)
	$GOPATH/src/goa.design/goa/codegen/generator/generate.go:62 +0x37c
main.main()
	$GOPATH/src/github.com/akm/goa_v2_simple_example/goa364214395/main.go:54 +0x2dd
```

## Steps to Reproduce the Problem (including complete and simple design if relevant)

```
$ mkdir -p $GOPATH/src/github.com/akm
$ cd $GOPATH/src/github.com/akm
$ git clone https://github.com/akm/goa_v2_simple_example.git
$ cd goa_v2_simple_example
$ goa gen github.com/akm/goa_v2_simple_example/design
```

## Note

If `Body` is removed, `goa gen` finishes without any error. 
https://github.com/akm/goa_v2_simple_example/blob/if_remove_body/design/person.go#L54

But `ListResponseBody` generated is not an array but a struct
https://github.com/akm/goa_v2_simple_example/commit/5eabc221188f7570504fa89577f333632bafb1fc#diff-c255176bae3232fc27e5dd12fbb14929

## Specifications

  - goa Version: https://github.com/goadesign/goa/commit/5cadea1d967fe93c7b9ef8bede7ed300b7e40e45
  - Platform (Linux/Windows etc.): Mac OS X 10.14.4 (18E226)

**Comment by nitinmohan87** [comment]
Thanks for the detailed bug report! This issue should be fixed by the PR above.

**Comment by akm** [comment]
@nitinmohan87 Thank you for fixing! `goa gen` doesn't raise any error with https://github.com/goadesign/goa/commit/e5cd7ab3a94fe0acbe89e7290fe85541b78e164a .
