### ISSUE TITLE
GOA v2 -- Leaving off the Token field for an OAuth method causes a panic

### ISSUE THREAD

**Issue by Grimkey** [goadesign/goa#2086]
When creating a new method that required a `Token`, when I accidentally forgot to include it in the payload, `goa gen` caused a hard to diagnose panic.

Here is a method that will crash (this is edited from https://github.com/goadesign/examples/blob/34577a438e956c1904238d8c4bdb5f704fb33d7c/security/design/design.go#L96)

```
	Method("secure", func() {
		Description("This action is secured with the jwt scheme")

		Security(JWTAuth, func() { // Use JWT to auth requests to this endpoint.
			Scope("api:read") // Enforce presence of "api:read" scope in JWT claims.
		})

		Payload(func() {
                        // MISSING FIELD FOR TOKEN HERE.
			Required("token")
		})

		Result(String)

		Error("invalid-scopes", String, "Token scopes are invalid")

		HTTP(func() {
			GET("/secure")
			Response(StatusOK)
			Response("invalid-scopes", StatusForbidden)
		})
	})
```

## Expected Behavior

To receive an error code indicating the problem, such as:

`service "secured_service" method "doubly_secure": payload - required field "token" does not exist in type object`

## Actual Behavior
Panic

```
exit status 2
panic:  is not the name of a child of the mapped attribute

goroutine 1 [running]:
goa.design/goa/expr.(*MappedAttributeExpr).Map(0xc000215320, 0xa8bd42, 0xd, 0x0, 0x0)
        /home/james/go/src/goa.design/goa/expr/mapped_attribute.go:124 +0x19d
goa.design/goa/expr.(*HTTPEndpointExpr).Finalize(0xc0002a2580)
        /home/james/go/src/goa.design/goa/expr/http_endpoint.go:478 +0x85a
goa.design/goa/eval.finalizeSet(0xc0001f77b0, 0x1, 0x1, 0x0, 0x0)
        /home/james/go/src/goa.design/goa/eval/eval.go:233 +0xae
goa.design/goa/expr.(*RootExpr).WalkSets(0xfbdde0, 0xaec558)
        /home/james/go/src/goa.design/goa/expr/root.go:121 +0xab2
goa.design/goa/eval.RunDSL(0x7ffe98c2818c, 0xc0001f4320)
        /home/james/go/src/goa.design/goa/eval/eval.go:55 +0x48e
main.main()
        /home/james/go/src/goa.design/examples/basic/goa753429668/main.go:47 +0x411
```

## Steps to Reproduce the Problem (including complete and simple design if relevant)
See comments below for the whole design file, then use Goa V2 to generate code.

## Specifications

  - goa Version: V2

> commit f1b9b0ebaef41459898c247dbc5a0dd7acea3d03 (HEAD -> v2, origin/v2, origin/master, origin/HEAD)
> Author: Nitin <nitinmohan87@gmail.com>
> Date:   Thu Apr 25 12:18:16 2019 -0700
> 
>    Add support for Params and Headers DSL (#2077)

  - Platform (Linux/Windows etc.): Ubuntu Linux 18.04.2 LTS running go1.12.2

**Comment by Grimkey** [comment]
Here is my repro file:

```
package design

import (
	. "goa.design/goa/dsl"
)

var _ = API("multi_auth", func() {
	Title("Security Example API")
	Description("This API demonstrates the use of the goa security DSL")
	Docs(func() { // Documentation links
		Description("Security example README")
		URL("https://github.com/goadesign/goa/tree/master/example/security/README.md")
	})
})

// JWTAuth defines a security scheme that uses JWT tokens.
var JWTAuth = JWTSecurity("jwt", func() {
	Description(`Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint. Supports scopes "api:read" and "api:write".`)
	Scope("api:read", "Read-only access")
	Scope("api:write", "Read and write access")
})

// APIKeyAuth defines a security scheme that uses API keys.
var APIKeyAuth = APIKeySecurity("api_key", func() {
	Description("Secures endpoint by requiring an API key.")
})

// BasicAuth defines a security scheme using basic authentication. The scheme
// protects the "signin" action used to create JWTs.
var BasicAuth = BasicAuthSecurity("basic", func() {
	Description("Basic authentication used to authenticate security principal during signin")
})

// OAuth2Auth defines a security scheme that uses OAuth2 tokens.
var OAuth2Auth = OAuth2Security("oauth2", func() {
	AuthorizationCodeFlow("/authorization", "/token", "/refresh")
	Description(`Secures endpoint by requiring a valid OAuth2 token retrieved via the signin endpoint. Supports scopes "api:read" and "api:write".`)
	Scope("api:read", "Read-only access")
	Scope("api:write", "Read and write access")
})

var _ = Service("secured_service", func() {
	Description("The secured service exposes endpoints that require valid authorization credentials.")

	Error("unauthorized", String, "Credentials are invalid")

	HTTP(func() {
		Response("unauthorized", StatusUnauthorized)
	})

	GRPC(func() {
		Response("unauthorized", CodeUnauthenticated)
	})

	Method("secure", func() {
		Description("This action is secured with the jwt scheme")

		Security(JWTAuth, func() { // Use JWT to auth requests to this endpoint.
			Scope("api:read") // Enforce presence of "api:read" scope in JWT claims.
		})

		Payload(func() {
			Required("token")
		})

		Result(String)

		Error("invalid-scopes", String, "Token scopes are invalid")

		HTTP(func() {
			GET("/secure")
			Response(StatusOK)
			Response("invalid-scopes", StatusForbidden)
		})
	})
})

// Creds defines the credentials to use for authenticating to service methods.
var Creds = Type("Creds", func() {
	Field(1, "jwt", String, "JWT token", func() {
		Example("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ")
	})
	Field(2, "api_key", String, "API Key", func() {
		Example("abcdef12345")
	})
	Field(3, "oauth_token", String, "OAuth2 token", func() {
		Example("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ")
	})
	Required("jwt", "api_key", "oauth_token")
})
```

**Comment by raphael** [comment]
Thanks for providing all the details, we'll look into it!

**Comment by Grimkey** [comment]
Looks like the problem is here: https://github.com/goadesign/goa/blob/7b882cca30dd9fea80402de66287ebedf35ad734/expr/http_endpoint.go#L473

`field` is assigned the value empty string.

**Comment by raphael** [comment]
Thank you, this is now fixed.
