### ISSUE TITLE
Self Referential Type with ArrayOf causes error

### ISSUE THREAD

**Issue by danapsimer** [goadesign/goa#2113]
Given the following design in a file named "design/design.go" in a module named "selfRefTypes"
```
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = API("selfRef", func() {
	Title("Self Reference")
})

var Person = Type("Person", func() {
	Attribute("name", String, "the person's name")
	Attribute("friends", ArrayOf("Person"), "the person's friends")
})

var _ = Service("selfRef", func() {
	Method("retrievePerson", func() {
		Payload(func() {
			Field(1, "personId", String, "the id of the person")
			Required("personId")
		})
		Result(Person)
		HTTP(func() {
			GET("/person/{personId}")
			Response(StatusOK)
		})
	})
})
```
the following command
`goa gen selfRefTypes/design`
produces the following output:
```
exit status 2
panic: reflect: call of reflect.Value.Set on zero Value

goroutine 1 [running]:
reflect.flag.mustBeExported(0x0)
	/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:215 +0xad
reflect.Value.Set(0x15cfce0, 0xc0000c1660, 0x195, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:1468 +0x40
reflect.Append(0x15a37e0, 0xc0000c1640, 0x97, 0xc000242928, 0x1, 0x1, 0x97, 0xc0002aca50, 0x0)
	/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:1964 +0xe3
goa.design/goa/v3/expr.(*Array).MakeSlice(0xc0000a81f0, 0xc0002acb10, 0x3, 0x3, 0x1330266, 0xa)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/expr/types.go:455 +0x18c
goa.design/goa/v3/expr.(*Array).Example(0xc0000a81f0, 0xc0002aca50, 0xc0000cd7a0, 0x90000c0002e61e0)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/expr/types.go:446 +0x126
goa.design/goa/v3/expr.(*AttributeExpr).Example(0xc0002ae210, 0xc0002aca50, 0x166e385, 0x4)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/expr/example.go:65 +0x1e6
goa.design/goa/v3/expr.(*Object).Example(0xc0000c0600, 0xc0002aca50, 0x1673218, 0x6)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/expr/types.go:562 +0x8f
goa.design/goa/v3/expr.(*UserTypeExpr).recExample(0xc0000c0620, 0xc0002aca50, 0x0)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/expr/user_type.go:94 +0x120
goa.design/goa/v3/expr.(*UserTypeExpr).Example(0xc0000c0620, 0xc0002aca50, 0xc0000e2200, 0x47)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/expr/user_type.go:78 +0x35
goa.design/goa/v3/expr.(*AttributeExpr).Example(0xc0002ae420, 0xc0002aca50, 0xc000242de8, 0x3)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/expr/example.go:65 +0x1e6
goa.design/goa/v3/codegen/service.buildMethodData(0xc0002b0000, 0xc0000c7240, 0x7, 0xc00017e280, 0xc0000b3f70, 0xc0000ca700)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/codegen/service/service_data.go:754 +0x598
goa.design/goa/v3/codegen/service.ServicesData.analyze(0xc000223e00, 0xc00017e280, 0x7)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/codegen/service/service_data.go:568 +0xe0b
goa.design/goa/v3/codegen/service.ServicesData.Get(0xc000223e00, 0x1678861, 0x7, 0x10)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/codegen/service/service_data.go:390 +0xa7
goa.design/goa/v3/codegen/service.File(0xc0000c7200, 0x10, 0xc00017e280, 0x3800d98)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/codegen/service/service.go:13 +0x5c
goa.design/goa/v3/codegen/generator.Service(0xc0000c7200, 0x10, 0xc00021f420, 0x2, 0x2, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/codegen/generator/service.go:23 +0x1bd
goa.design/goa/v3/codegen/generator.Generate(0x7ffeefbff866, 0x1, 0x166cc63, 0x3, 0x0, 0x0, 0x0, 0xc0002149f0, 0x0)
	/Users/danap/dev/bluesoft/go/pkg/mod/goa.design/goa/v3@v3.0.0/codegen/generator/generate.go:62 +0x3c1
main.main()
	/Users/danap/dev/bluesoft/oss/goaexamples/selfRefTypes/goa118004280/main.go:62 +0x23a
```

**Comment by raphael** [comment]
Thank you, I was able to reproduce the issue and will have a look.

**Comment by fafnirbcrow** [comment]
This looks to be the same/similar error as #2108
