### ISSUE TITLE
V3: 3.0.1 generator panics with designs valid for 3.0.0

### ISSUE THREAD

**Issue by ilmaruk** [goadesign/goa#2139]
This design:
```package design

import (
    . "goa.design/goa/v3/dsl"
)

var _ = API("test-api", func() {
    Title("Just a test")
    Server("test-server", func() {
        Host("localhost", func() {
            URI("http://localhost:8080")
        })
    })
})

var innerResType = ResultType("inner-res-type", func() {
    Attributes(func() {
        Attribute("name", String)
    })
})

var outerResType = ResultType("outer-res-type", func() {
    Attributes(func() {
        Attribute("items1", CollectionOf(innerResType))
        Attribute("items2", CollectionOf(innerResType))
    })
})

var _ = Service("test-service", func() {
    Method("get", func() {
        Result(outerResType)
        HTTP(func() {
            GET("/foo")
            Response(StatusOK)
        })
    })
})
```
can be used to successfully generate code in `3.0.0`, but causes the generator to panic in `3.0.1`:
```$ goa gen goa-test/design
exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x88172a]

goroutine 1 [running]:
goa.design/goa/v3/codegen.AppendHelpers(0x0, 0x1, 0x1, 0xc000373000, 0x2, 0x2, 0xc000365980, 0xc0003652f0, 0xa7a06b)
	/go/pkg/mod/goa.design/goa/v3@v3.0.1/codegen/transformer.go:127 +0x5a
goa.design/goa/v3/http/codegen.buildResponseBodyType(0xc0002a2d10, 0xc0003604d0, 0xc00028e4d0, 0x1, 0xc000346320, 0xc000374480, 0x0)
	/go/pkg/mod/goa.design/goa/v3@v3.0.1/http/codegen/service_data.go:2118 +0xd26
goa.design/goa/v3/http/codegen.buildResponses(0xc00028e4d0, 0xc0003604d0, 0x1, 0xc000374480, 0xc000311300, 0x19, 0xc00033c0a0)
	/go/pkg/mod/goa.design/goa/v3@v3.0.1/http/codegen/service_data.go:1376 +0x2255
```
etc.

It seems to me that using a custom ResultType (`innerResType` in the example above) twice in the definition of the ResultType used as Result (`outerResType`) is causing the issue.

**Comment by raphael** [comment]
Thank you, this is fixed in https://github.com/goadesign/goa/pull/2133.
