### ISSUE TITLE
v3: goa gen panic while doing example for ArrayOf string enum

### ISSUE THREAD

**Issue by nickchen** [goadesign/goa#2205]
Got the following error while running `goa gen pet/design`.

Scrubbed name and path.

```
$ goa gen pet/design
exit status 2
panic: reflect.Set: value of type string is not assignable to type map[string]interface {}

goroutine 1 [running]:
reflect.Value.assignTo(0x15b0980, 0xc00028ed80, 0x98, 0x168a8bd, 0xb, 0x15d3ec0, 0x0, 0xc000025c00, 0x1bd4420, 0x2940008)
        /usr/local/go/src/reflect/value.go:2339 +0x437
reflect.Value.Set(0x15d3ec0, 0xc00031e240, 0x195, 0x15b0980, 0xc00028ed80, 0x98)
        /usr/local/go/src/reflect/value.go:1473 +0xa8
reflect.Append(0x15a7960, 0xc00031e220, 0x97, 0xc0002527d0, 0x1, 0x1, 0x97, 0xc000297d70, 0x15b0980)
        /usr/local/go/src/reflect/value.go:1964 +0xe3
goa.design/goa/v3/expr.(*Array).MakeSlice(0xc00022e2e8, 0xc000297e60, 0x3, 0x3, 0x2940008, 0x0)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/types.go:459 +0x18c
goa.design/goa/v3/expr.(*Array).Example(0xc00022e2e8, 0xc000297d70, 0xc000320000, 0x4b0000c00028ed60)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/types.go:450 +0x18d
goa.design/goa/v3/expr.(*AttributeExpr).Example(0xc0002c02c0, 0xc000297d70, 0x1678721, 0x6)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/example.go:65 +0x1e6
goa.design/goa/v3/expr.(*Object).Example(0xc00000e6e0, 0xc000297d70, 0x167b281, 0x7)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/types.go:566 +0x8f
goa.design/goa/v3/expr.(*UserTypeExpr).recExample(0xc00000e700, 0xc000297d70, 0xc00028ed30)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/user_type.go:94 +0x120
goa.design/goa/v3/expr.(*UserTypeExpr).Example(0xc00000e700, 0xc000297d70, 0x15b0980, 0xb60000c00028ed40)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/user_type.go:78 +0x35
goa.design/goa/v3/expr.(*AttributeExpr).Example(0xc0002c04d0, 0xc000297d70, 0x167256d, 0x4)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/example.go:65 +0x1e6
goa.design/goa/v3/expr.(*Object).Example(0xc00000e720, 0xc000297d70, 0x1670b13, 0x3)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/types.go:566 +0x8f
goa.design/goa/v3/expr.(*UserTypeExpr).recExample(0xc00000e740, 0xc000297d70, 0x0)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/user_type.go:94 +0x120
goa.design/goa/v3/expr.(*UserTypeExpr).Example(0xc00000e740, 0xc000297d70, 0xc000100200, 0x3a)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/user_type.go:78 +0x35
goa.design/goa/v3/expr.(*AttributeExpr).Example(0xc0002c0790, 0xc000297d70, 0xc000252de8, 0x3)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/expr/example.go:65 +0x1e6
goa.design/goa/v3/codegen/service.buildMethodData(0xc0002ac120, 0xc000025700, 0x8, 0xc000194300, 0xc00028ea90, 0xc000025700)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/codegen/service/service_data.go:755 +0x5fa
goa.design/goa/v3/codegen/service.ServicesData.analyze(0xc00027ecc0, 0xc000194300, 0x8)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/codegen/service/service_data.go:569 +0xe3a
goa.design/goa/v3/codegen/service.ServicesData.Get(0xc00027ecc0, 0x167ed7f, 0x8, 0x7)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/codegen/service/service_data.go:390 +0xa7
goa.design/goa/v3/codegen/service.File(0xc0000256c0, 0x7, 0xc000194300, 0x2940008)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/codegen/service/service.go:13 +0x5c
goa.design/goa/v3/codegen/generator.Service(0xc0000256c0, 0x7, 0xc000259d80, 0x2, 0x2, 0x2, 0x2, 0x0, 0x0, 0x1036094)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/codegen/generator/service.go:23 +0x1bd
goa.design/goa/v3/codegen/generator.Generate(0x7ffeefbff83e, 0x1, 0x1670d2c, 0x3, 0x0, 0x0, 0x0, 0xc00022d2c0, 0x0)
        /Users//pkg/mod/goa.design/goa/v3@v3.0.3/codegen/generator/generate.go:62 +0x3c1
main.main()
        /Users//pet/goa395738727/main.go:62 +0x23a
```

```
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = API("Pet", func() {
	Title("Pet demo project to test out goa capabilities")
	HTTP(func() {
		Consumes("application/json")
		Produces("application/json")
	})
	Server("app", func() {
		Host("localhost", func() {
			URI("https://localhost:8080")
		})
	})
})

var _ = Service("PetStore", func() {

	HTTP(func() {
		Path("/api")
	})
	Method("get", func() {
		Description("Gets a single Pet.")
		Payload(func() {
			Attribute("pet_id", String, "id of the strategy")
			Required("pet_id")
		})

		Result(Pet)
		Error("not_found", String, "Pet not found")
		HTTP(func() {
			GET("/pets/{pet_id}")
			Response(StatusOK, func() {
				// this sets the name for the reference, so we don't create a duplicated object
				Body(Pet)
			})
			Response("not_found", StatusNotFound)
		})
	})
	Method("list", func() {
		Description("Gets a list of all Pets.")
		Result(Pets)
		HTTP(func() {
			GET("/pets")
			Response(StatusOK, func() {
				Body(Pets)
			})
		})
	})
})

var PetType = Type("PetType", String, func() {
	Enum("FOUR_LEG", "TWO_LEG")
})

var PetAttribute = Type("PetAttribute", String, func() {
	Enum("MEAT", "VEGGIE", "LIKES_SUN", "DOESNOT_LIKE_SUN")
})

var PetAttributeContainer = Type("PetMode", func() {
	Attribute("values", String)
	Attribute("attributes", ArrayOf(PetAttribute))
})

var Pet = Type("Pet", func() {
	Attribute("name", String, `name of the pet`, func() {
		MaxLength(24)
	})
	Attribute("type", PetType)
	Attribute("attributes", PetAttributeContainer)
})

var Pets = Type("Pets", ArrayOf(Pet))
```

Workaround by changing

```
var PetAttributeContainer = Type("PetMode", func() {
	Attribute("values", String)
	Attribute("attributes", ArrayOf(PetAttribute), func() {
		Example("Simple Example", func() {
			Value([]string{"MEAT", "VEGGIE"})
		})
	})
})
```

Using `goa version v3.0.3`

**Comment by nitinmohan87** [comment]
Thanks for the report! Not sure I follow what the issue is here. I am able to set array examples as shown below
```
var _ = Service("foo", func() {
  Method("show", func() {
    Payload(func() {
      Attribute("string_array", ArrayOf(String), func() {
        Example([]string{"hello"})
      })
    })

    HTTP(func() {
      GET("/")
    })
  })
})
```
I wasn't aware you could use the `Type` DSL like this. Learned something new :) . Not sure if we support this at the moment (buggy!) though the docs says we must.
```
var PetType = Type("PetType", String, func() {
	Enum("FOUR_LEG", "TWO_LEG")
})
```
