### ISSUE TITLE
v1: Meta map not included in ErrorResponse

### ISSUE THREAD

**Issue by MarkSonghurst** [goadesign/goa#2275]
Hi there.
Using the v1 DSL, I've specified some Attributes to use minimum and maximums and format:
```	
Attribute("firstname", String, "firstname of user", func() {
		MinLength(2)
		MaxLength(255)
		Example("John")
	})
Attribute("username", String, "email address of user", func() {
		Format("email")
	})
Required("username")
```

This is successfully resulting in generated code in my app/user_types.go file:
```
// Validate validates the UserCreateSelf type instance.
func (ut *UserCreateSelf) Validate() (err error) {
<snip>
	if utf8.RuneCountInString(ut.Firstname) < 2 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`type.firstname`, ut.Firstname, utf8.RuneCountInString(ut.Firstname), 2, true))
	}
	if utf8.RuneCountInString(ut.Firstname) > 255 {
		err = goa.MergeErrors(err, goa.InvalidLengthError(`type.firstname`, ut.Firstname, utf8.RuneCountInString(ut.Firstname), 255, false))
	}
<snip>
	if ut.Username != nil {
		if err2 := goa.ValidateFormat(goa.FormatEmail, *ut.Username); err2 != nil {
			err = goa.MergeErrors(err, goa.InvalidFormatError(`request.username`, *ut.Username, goa.FormatEmail, err2))
		}
	}
<snip>
        return
}
```
All good so far.
However, when my API endpoint is called with request attributes which fail the validation, the response body structure is missing the `meta` attribute map:

```
{ 
  code: "bad_request"
  detail: "[JQSAk5Ql] 400 invalid_request: length of request.firstname must be greater than or equal to 2 but got value "" (len=0); request.username must be formatted as a email but got value "", invalid email value, mail: no address, attribute: request.username, value: , len: 0, comp: greater than or equal to, expected: email, error: invalid email value, mail: no address"
  id: "yUDZyPGj"
  status: 400
}
```

The response has the content-type `application/vnd.goa.error` which in my generated Swagger file should include the `meta` map.

The string used in `detail` is coming from goa/error.go `func (e *ErrorResponse) Error() string` so the `meta` map is being used within the `detail` string.

The ErrorResponse struct in in goa/error.go says to omit the map if it's empty, so perhaps the map is being lost somewhere by Goa? 
This only appears related to attribute validation, as when I generate my own errors:

```
	if err != nil {
			return goa.ErrInternal(err, "message", "Token generation issue")
		}
```
I get the `meta` map populated in the response body:

```
{
    "id": "DS4gwdRc",
    "code": "bad_request",
    "status": 400,
    "detail": "User does not have Role \"Unknown\" (1) in Organisation \"Global\" (0)",
    "meta": {
        "message": "Token generation issue"
    }
}
```
(response content-type header is `application/vnd.goa.error`)

I'm limited to using Goa v1 so I don't know if this issue exists in other Goa versions.

**Comment by raphael** [comment]
Thank you for the report, happy to help troubleshoot but at this point I'm focusing on supporting v2 and v3 so probably won't get to this for a little while.

**Comment by MarkSonghurst** [comment]
I have made some progress by debugging the error.go NewErrorClass function (please excuse the log.Println statements:
```// NewErrorClass creates a new error class.
// It is the responsibility of the client to guarantee uniqueness of code.
func NewErrorClass(code string, status int) ErrorClass {
	return func(message interface{}, keyvals ...interface{}) error {
		var msg string
		switch actual := message.(type) {
		case ServiceMergeableError:
			log.Println("IT'S A ServiceMergeableError !!!!!")
			return actual
		case ServiceError:
			log.Println("IT'S A ServiceError !!!!!")
			return actual
		case string:
			log.Println("IT'S A STRING")
			msg = actual
```
By switching on the ServiceError type I was able to ensure the meta map remained in my response. I also added a case for the ServiceMergeableError type (possibly unnecessary..?) 
This gives me the response:

```{
    "id": "ftHWqcoZ",
    "code": "invalid_request",
    "status": 400,
    "detail": "request.username must be formatted as a email but got value \"unit_test1570715083592.test\", invalid email value, mail: missing '@' or angle-addr",
    "meta": {
        "attribute": "request.username",
        "error": "invalid email value, mail: missing '@' or angle-addr",
        "expected": "email",
        "value": "unit_test1570715083592.test"
    }
}
```

I'm a bit wary that I need to switch on the ServiceError and ServiceMergeableError types, or have I have uncovered a bug?

One issue I noticed having added this code, is if you use and then fail more than 1 validation rule then the meta map is being messed up, so I would need to support that (meta being a JSON map to an array per attribute perhaps?)

```
{
    "id": "Opmdxu6a",
    "code": "invalid_request",
    "status": 400,
    "detail": "request.username must be formatted as a email but got value \"unit_test1570715901314.test\", invalid email value, mail: missing '@' or angle-addr; length of request.username must be less than or equal to 1 but got value \"unit_test1570715901314.test\" (len=27)",
    "meta": {
        "attribute": "request.username",
        "comp": "less than or equal to",
        "error": "invalid email value, mail: missing '@' or angle-addr",
        "expected": 1,
        "len": 27,
        "value": "unit_test1570715901314.test"
    }
}
```
...perhaps this is why the switching above was not originally done?

**Comment by MarkSonghurst** [comment]
Fixed this in my own fork.

**Comment by raphael** [comment]
Thank you for documenting the above! Question: what calls the `NewErrorClass` function? The intent here is that the metadata should be provided when a specific instance of an error is created rather than a new class of errors.

**Comment by MarkSonghurst** [comment]
Hi @raphael 
I'll gladly admit I've been round the houses several times figuring out how errors work from Goa's validation layer - it was quite heavy-going! Ultimately though I have been able to address my requirement, which was to get richer meta data in the validation responses back to our clients. I was mostly able to achieve this using the ServiceMergeableError support added by someone else. Hence why I've closed this ticket and not offered a PR.

> Question: what calls the NewErrorClass function

In my fork it remains the same as the v1 branch -  the result from NewErrorClass is being set during initialisation in goa/error.go for ErrInvalidRequest. This in turn is used by the Goa validation layer.
```
ErrInvalidRequest = NewErrorClass("invalid_request", 400)
```

I made some changes to my fork of v1 a while back so I could use go modules and I can no longer recall everything that was required in order to get a fresh pull of the goadesign goa v1 branch working with modules. The build system for my API no longer works outside go modules. Anyway, the outcome of this is that I can only provide the following stack dump from my fork, which probably isn't very helpful to you:

```
INFO[0006] error.go:135: a function generated by NewErrorClass is being called with message length of request.surname must be greater than or equal to 2 but got value "" (len=0) (type: string) and keyvals [attribute request.surname value  len 0 comp greater than or equal to expected 2] 
goroutine 56 [running]:
runtime/debug.Stack(0xc0000a8050, 0x2, 0xc0005985a0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/goadesign/goa.NewErrorClass.func1(0x10f0c60, 0xc000557460, 0xc000425cc0, 0xa, 0xa, 0xc00041a720, 0x55)
	/home/centos/src/MarkSonghurst/goa/error.go:136 +0x11c
github.com/goadesign/goa.InvalidLengthError(0x140e3f9, 0xf, 0x10f0c60, 0x20e4900, 0x0, 0x2, 0xc000563401, 0x30, 0x8)
	/home/centos/src/MarkSonghurst/goa/error.go:254 +0x375
bitbucket.org/scanimal/apiv3-vet/app.(*userCreateSelf).Validate(0xc0005c4300, 0xc00053d4f0, 0x1213e60)
	/home/centos/src/apiv3-vet/app/user_types.go:5799 +0x47f
bitbucket.org/scanimal/apiv3-vet/app.unmarshalCreateselfUsersPayload(0x16998a0, 0xc000574d20, 0xc0003d8d90, 0xc000435000, 0xc000435000, 0xc000574c60)
	/home/centos/src/apiv3-vet/app/controllers.go:2135 +0xd1
github.com/goadesign/goa.(*Controller).MuxHandler.func1(0x1692ba0, 0xc0003ea620, 0xc000435000, 0xc000574c60)
	/home/centos/src/MarkSonghurst/goa/service.go:331 +0x432
github.com/goadesign/goa.(*mux).Handle.func1(0x1692ba0, 0xc0003ea620, 0xc000435000, 0x0)
	/home/centos/src/MarkSonghurst/goa/mux.go:69 +0x1c5
github.com/dimfeld/httptreemux.(*TreeMux).ServeLookupResult(0xc0001d9540, 0x1692ba0, 0xc0003ea620, 0xc000435000, 0xc8, 0xc00040bb90, 0x0, 0x0)
	/home/centos/go/pkg/mod/github.com/dimfeld/httptreemux/v5@v5.0.2/router.go:247 +0x169
github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc0001d9540, 0x1692ba0, 0xc0003ea620, 0xc000435000)
	/home/centos/go/pkg/mod/github.com/dimfeld/httptreemux/v5@v5.0.2/router.go:268 +0x109
github.com/goadesign/goa.(*mux).ServeHTTP(0xc0001cd4a0, 0x1692ba0, 0xc0003ea620, 0xc000435000)
	/home/centos/src/MarkSonghurst/goa/mux.go:100 +0x4c
net/http.serverHandler.ServeHTTP(0xc0003e4000, 0x1692ba0, 0xc0003ea620, 0xc000435000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000425a40, 0x16997e0, 0xc00057c300)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
INFO[0006] error.go:135: a function generated by NewErrorClass is being called with message [uD6M0vVv] 400 invalid_request: length of request.surname must be greater than or equal to 2 but got value "" (len=0), len: 0, comp: greater than or equal to, expected: 2, attribute: request.surname, value:  (type: *goa.ErrorResponse) and keyvals [] 
goroutine 56 [running]:
runtime/debug.Stack(0xc0000a8050, 0x2, 0xc000420780)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/goadesign/goa.NewErrorClass.func1(0x121f7e0, 0xc00057c580, 0x0, 0x0, 0x0, 0xc00057c580, 0x16998a0)
	/home/centos/src/MarkSonghurst/goa/error.go:136 +0x11c
github.com/goadesign/goa.(*Controller).MuxHandler.func1(0x1692ba0, 0xc0003ea620, 0xc000435000, 0xc000574c60)
	/home/centos/src/MarkSonghurst/goa/service.go:336 +0x4c0
github.com/goadesign/goa.(*mux).Handle.func1(0x1692ba0, 0xc0003ea620, 0xc000435000, 0x0)
	/home/centos/src/MarkSonghurst/goa/mux.go:69 +0x1c5
github.com/dimfeld/httptreemux.(*TreeMux).ServeLookupResult(0xc0001d9540, 0x1692ba0, 0xc0003ea620, 0xc000435000, 0xc8, 0xc00040bb90, 0x0, 0x0)
	/home/centos/go/pkg/mod/github.com/dimfeld/httptreemux/v5@v5.0.2/router.go:247 +0x169
github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc0001d9540, 0x1692ba0, 0xc0003ea620, 0xc000435000)
	/home/centos/go/pkg/mod/github.com/dimfeld/httptreemux/v5@v5.0.2/router.go:268 +0x109
github.com/goadesign/goa.(*mux).ServeHTTP(0xc0001cd4a0, 0x1692ba0, 0xc0003ea620, 0xc000435000)
	/home/centos/src/MarkSonghurst/goa/mux.go:100 +0x4c
net/http.serverHandler.ServeHTTP(0xc0003e4000, 0x1692ba0, 0xc0003ea620, 0xc000435000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000425a40, 0x16997e0, 0xc00057c300)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
INFO[0006] started                                       POST="/users/self?role=vet" action=createself ctrl=UsersController from=XXX.XXX.XXX.XXX req_id=c4F8VfdwKy-1
INFO[0006] completed                                     action=createself bytes=260 ctrl=UsersController error=uD6M0vVv fields.time="153.298µs" req_id=c4F8VfdwKy-1 status=400
```

It's interesting that the function generated by NewErrorClass is being called twice. Possibly this is 2 different functions generated by NewErrorClass, although the deliberate error I'm testing with is a single MinLength validation error. I ran out steam trying to figure this out. It doesn't appear to affect my end goal, so I consider it the magic behind the curtain and will blissfully ignore it :-)

My fork is https://github.com/goadesign/goa/compare/v1...MarkSonghurst:CustomErrorHandling if you want a peek.  

Thanks for all your work on Goa.
