### ISSUE TITLE
Panic while parsing headers spec

### ISSUE THREAD

**Issue by xlab** [goadesign/goa#2451]
This is unrelated to recent changes to headers processing, but I hope it'd be fixed. It's not fixed yet and I don't know the minimal example, but there is a real example:

```go

			HTTP(func() {
				POST("/rest/getStuff")

				Response(StatusOK, withRespHeaders("Success"))
				Response("bad_request", StatusBadRequest, withRespHeaders("Validation error"))
				Response("not_found", StatusNotFound, withRespHeaders("Not found"))
				Response("rate_limit", StatusTooManyRequests, withRespHeaders("Too many requests - Rate limit exceeded"))
				Response("internal", StatusInternalServerError, withRespHeaders("Internal Server Error"))
				Response("not_implemented", StatusNotImplemented, withRespHeaders("Not implemented"))
			})
		})
	}
})

func withRespHeaders(desc string) func() {
	return func() {
		Description(desc)

		Header("rLimitLimit:X-Rate-Limit-Limit", Int)
		Header("rLimitRemaining:X-Rate-Limit-Remaining", Int)
		Header("rLimitReset:X-Rate-Limit-Reset", Int)
	}
}
```

Results in panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14a3fcd]

goroutine 1 [running]:
goa.design/goa/v3/codegen.(*AttributeContext).IsPrimitivePointer(0xc00035aff0, 0x16f5f46, 0xb, 0xc000329b80, 0x10)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/codegen/transformer.go:184 +0x8d
goa.design/goa/v3/http/codegen.extractHeaders.func1(0x16f5f46, 0xb, 0x16f5f52, 0x12, 0x0, 0xc0003e5600, 0xa0, 0xa0)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/http/codegen/service_data.go:2306 +0x82e
goa.design/goa/v3/codegen.WalkMappedAttr(0xc0003dcf20, 0xc000558998, 0x0, 0x14a2753)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/codegen/walk.go:29 +0x130
goa.design/goa/v3/http/codegen.extractHeaders(0xc0003dcf20, 0xc000329b80, 0xc00035aff0, 0xc00025ca80, 0x4, 0xc0004e3260, 0x57)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/http/codegen/service_data.go:2274 +0x9b
goa.design/goa/v3/http/codegen.buildErrorsData(0xc000396000, 0xc0004f70e0, 0xc00054e380, 0x174, 0xc0004f4140)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/http/codegen/service_data.go:1587 +0x1161
goa.design/goa/v3/http/codegen.ServicesData.analyze(0xc0002762a0, 0xc000329ad0, 0x7)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/http/codegen/service_data.go:821 +0x2a87
goa.design/goa/v3/http/codegen.ServicesData.Get(0xc0002762a0, 0x16c2003, 0x7, 0xc00023ccc0)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/http/codegen/service_data.go:598 +0xb1
goa.design/goa/v3/http/codegen.serverFile(0xc000538030, 0x2f, 0xc000329ad0, 0xc000419120)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/http/codegen/server.go:28 +0x62
goa.design/goa/v3/http/codegen.ServerFiles(0xc000538030, 0x2f, 0x1c1c1c0, 0xc0002679f0, 0x50, 0x50)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/http/codegen/server.go:18 +0xcf
goa.design/goa/v3/codegen/generator.Transport(0xc000538030, 0x2f, 0xc00047a080, 0x3, 0x4, 0x9, 0x10, 0x9, 0x0, 0x0)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/codegen/generator/transport.go:26 +0x168
goa.design/goa/v3/codegen/generator.Generate(0x7ffeefbffa16, 0x9, 0x16b76df, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/xlab/Documents/dev/go/pkg/mod/goa.design/goa/v3@v3.0.9/codegen/generator/generate.go:82 +0x55e
main.main()
```

The code in question:

```go
// IsPrimitivePointer returns true if the attribute with the given name is a
// primitive pointer in the given parent attribute.
func (a *AttributeContext) IsPrimitivePointer(name string, att *expr.AttributeExpr) bool {
	if at := att.Find(name); at != nil && at.Type == expr.Any || at.Type == expr.Bytes { // panics here
		return false
	}
	if a.Pointer {
		return true
	}
	if a.IgnoreRequired {
		return false
	}
	return att.IsPrimitivePointer(name, a.UseDefault)
}
```

**Comment by raphael** [comment]
Thank you for the report! a couple of questions:
1. Can you please provide a minimal but complete design that reproduces the issue?
2. Do the corresponding method result types contain the attributes being identified in the `Header` DSL?

**Comment by raphael** [comment]
This may be fixed by #2452 - not sure without a complete repro, would you mind verifying? thanks!

**Comment by xlab** [comment]
Thanks for such swift resolution!
The codegen works now, I'll report an additional issue if I could not achieve my goal, but this problem is gone now. ✨

**Comment by xlab** [comment]
Thank you for a swift response, unfortunately this fix doesn't solve the problem, I'll try to acquire a reproducible case.
