### ISSUE TITLE
v3: Panic when parsing Parent DSL

### ISSUE THREAD

**Issue by ikawaha** [goadesign/goa#2461]
Panic in the processing of the Attribute of the endpoint that refers to the parent of the parent.

# Example design

calc -> parent -> ancestor

```go
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = Service("ancestor", func() {
	Method("show", func() {
		Payload(func() {
			Attribute("p")
		})
		HTTP(func() {
			GET("/ancestor/{p}")
		})
	})
})

var _ = Service("parent", func() {
	HTTP(func() {
		Parent("ancestor")
	})
	Method("show", func() {
		Payload(func() {
			Attribute("x")
		})
		HTTP(func() {
			GET("/parent/{x}")
		})
	})
})

var _ = Service("calc", func() {
	HTTP(func() {
		Parent("parent")

	})

	Method("add", func() {
		Payload(func() {
			Attribute("a")
		})
		HTTP(func() {
			GET("/add/{a}")
		})
	})
})
```

```shellsession
$ goa gen calc/design
exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x130c6a3]

goroutine 1 [running]:
goa.design/goa/v3/expr.(*dupper).DupAttribute(0xc0001e4b88, 0x0, 0xc000348680)
	/Users/ikawaha/go/src/goa.design/goa/expr/dup.go:41 +0x73
goa.design/goa/v3/expr.(*dupper).DupType(0xc0001e4b88, 0x17d4b40, 0xc0003485c0, 0x0, 0x20)
	/Users/ikawaha/go/src/goa.design/goa/expr/dup.go:78 +0x117
goa.design/goa/v3/expr.Dup(0x17d4b40, 0xc0003485c0, 0xc0003485c0, 0x1309558)
	/Users/ikawaha/go/src/goa.design/goa/expr/dup.go:7 +0x11f
goa.design/goa/v3/expr.NewMappedAttributeExpr(0xc0001e4e98, 0xc0003465de)
	/Users/ikawaha/go/src/goa.design/goa/expr/mapped_attribute.go:53 +0x1d1
goa.design/goa/v3/expr.(*HTTPEndpointExpr).PathParams(0xc000286240, 0x3)
	/Users/ikawaha/go/src/goa.design/goa/expr/http_endpoint.go:129 +0x290
goa.design/goa/v3/http/codegen.ServicesData.analyze(0xc0002307b0, 0xc00027a160, 0x4)
	/Users/ikawaha/go/src/goa.design/goa/http/codegen/service_data.go:672 +0x146e
goa.design/goa/v3/http/codegen.ServicesData.Get(0xc0002307b0, 0x16904b5, 0x4, 0x8)
	/Users/ikawaha/go/src/goa.design/goa/http/codegen/service_data.go:598 +0xb1
goa.design/goa/v3/http/codegen.serverFile(0xc0001ef0f0, 0x8, 0xc00027a160, 0xc000229d80)
	/Users/ikawaha/go/src/goa.design/goa/http/codegen/server.go:28 +0x62
goa.design/goa/v3/http/codegen.ServerFiles(0xc0001ef0f0, 0x8, 0x1bcff80, 0xc0000bccd0, 0x50, 0x50)
	/Users/ikawaha/go/src/goa.design/goa/http/codegen/server.go:18 +0xcf
goa.design/goa/v3/codegen/generator.Transport(0xc0001ef0f0, 0x8, 0xc0002974a0, 0x2, 0x2, 0x9, 0x10, 0x9, 0x0, 0x0)
	/Users/ikawaha/go/src/goa.design/goa/codegen/generator/transport.go:26 +0x168
goa.design/goa/v3/codegen/generator.Generate(0x7ffeefbff64e, 0x1, 0x168ef38, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ikawaha/go/src/goa.design/goa/codegen/generator/generate.go:82 +0x55e
main.main()
	/Users/ikawaha/go/src/github.com/ikawaha/calc/goa984547159/main.go:59 +0x20c
```

# What caused the bug?

We have a test case with a similar design, but this test worked.
* https://github.com/goadesign/goa/blob/e3bc3dd6322d9258fb07e886ef0c59681f8688b4/expr/http_endpoint_test.go#L132-L169
* https://github.com/goadesign/goa/blob/e3bc3dd6322d9258fb07e886ef0c59681f8688b4/expr/testdata/endpoint_dsls.go#L254-L305

It seems that `NewMappedAttributeExpr ()` panics by duplicating attributes containing nil.

```go
// DupType creates a copy of the given data type.
func (d *dupper) DupType(t DataType) DataType {
	if t == Empty {
		// Don't dup Empty so that code may check against it.
		return t
	}
	switch actual := t.(type) {
	case Primitive:
		return t
	case *Array:
		return &Array{ElemType: d.DupAttribute(actual.ElemType)}
	case *Object:
		res := &Object{}
		for _, nat := range *actual {
			fmt.Printf("\tnat: %#+v\n", nat)
			if nat.Attribute == nil {
				fmt.Println("↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑")
			}
			res.Set(nat.Name, d.DupAttribute(nat.Attribute))
		}
		return res
```

```shellsession
...snip
	nat: &expr.NamedAttributeExpr{Name:"p", Attribute:(*expr.AttributeExpr)(nil)}
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x130c6a3]
```

**Comment by raphael** [comment]
Thank you for the bug report. The issue is that the code that adds parent params that are not explicitly defined in the payload does not add grand parent attributes (https://github.com/goadesign/goa/blob/v3/expr/http_endpoint.go#L196-L215).

I am wondering if it wouldn't be better to remove this code and instead require that designs be explicit and list the parent attributes in payloads. So the design in this case would have to look like:

```go
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = Service("ancestor", func() {
	Method("show", func() {
		Payload(func() {
			Attribute("p")
		})
		HTTP(func() {
			GET("/ancestor/{p}")
		})
	})
})

var _ = Service("parent", func() {
	HTTP(func() {
		Parent("ancestor")
	})
	Method("show", func() {
		Payload(func() {
			Attribute("p")  // explicitly defined!
			Attribute("x")
		})
		HTTP(func() {
			GET("/parent/{x}")
		})
	})
})

var _ = Service("calc", func() {
	HTTP(func() {
		Parent("parent")

	})

	Method("add", func() {
		Payload(func() {
			Attribute("p")  // explicitly defined!
			Attribute("x")  // explicitly defined!
			Attribute("a")
		})
		HTTP(func() {
			GET("/add/{a}")
		})
	})
})
```

It seems good that the payload design be explicit and lists all the attributes even if the HTTP transport mapping comes from a parent. We could have a nice error message that explains this need in case the designer forgets to add the attribute. What do you think?

**Comment by ikawaha** [comment]
Thank you for considering my report!

I like the behavior of v1's Parent DSL because copying the same definition many times can make a mistake. Explicitly indicating the attributes inherited by the Parent DSL is the right way, but isn't it inconvenient?

What about the following specification:
* Parent DSL cannot be specified in multiple,
* Parent DSL copies attributes.

**Comment by raphael** [comment]
Yes, having to repeat the inherited parameter attributes isn't convenient - I am just wondering if it's a better trade-off as opposed to implicit complicated logic. I am not sure at this point :). Can you expand a little bit what you mean by "Parent DSL cannot be specified multiple", do you mean that the following would be incorrect?
```go
var _ = Service("calc", func() {
	HTTP(func() {
		Parent("parent")
		Parent("parent2")
	})
```
If so that makes sense and I think that's already the case? Am I understanding correctly that the specification you are suggesting is already the one that Goa v2/v3 is trying to implement (but that it  currently has the issue described above)?

**Comment by ikawaha** [comment]
I understand that the above example is incorrect. I couldn't express it well, what I wanted to say is that Parent DSL should not be nested. In the current version, it seems to work without problems with Parent DSL which does not nest.

```
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = Service("ancestor", func() {
	Method("show", func() {
		Payload(func() {
			Attribute("p")
		})
		HTTP(func() {
			GET("/ancestor/{p}")
		})
	})
})

var _ = Service("parent", func() {
	HTTP(func() {
		Parent("ancestor")   // ← OK, It is not nested.
	})
	Method("show", func() {
		Payload(func() {
			Attribute("x")
		})
		HTTP(func() {
			GET("/parent/{x}")
		})
	})
})

var _ = Service("calc", func() {
	HTTP(func() {
		Parent("parent")    // ← NG, This is not allowed because it is nested.
	})

	Method("add", func() {
		Payload(func() {
			Attribute("a")
		})
		HTTP(func() {
			GET("/add/{a}")
		})
	})
})
```

**Comment by raphael** [comment]
I see, thank you for the clarification. That seems to be a legitimate case though, there are cases where resources are nested like in the above so we should probably make it work.
