### ISSUE TITLE
Error: goagen panic runtime error when set INTEGER type Minimum(0)

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#259]
I updated new commit just now, and run test code with defined an attribute inside this `MediaType` define:

```go
var StatisticData = MediaType("application/testcode+json", func() {
	Attributes(func() {
		Attribute("amount", Integer, "Item amount", func() {
			Minimum(0)
		})
	})
...

```

running `goagen bootstrap -d ...` ,  it creates runtime error:

```
$ goagen bootstrap -d patest/design
exit status 2
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x4c8bae pc=0x4c8bae]

goroutine 1 [running]:
github.com/goadesign/goa/design.(*exampleGenerator).generateValidatedMinValueExample(0xc8201e36d0, 0x0, 0x0, 0x0)
	/CODEPATH/go/project/src/github.com/goadesign/goa/design/example.go:208 +0x8e
github.com/goadesign/goa/design.(*exampleGenerator).generate(0xc8201e36d0, 0x0, 0x0)
	CODEPATH/go/project/src/github.com/goadesign/goa/design/example.go:54 +0x4c2
github.com/goadesign/goa/design.(*AttributeDefinition).GenerateExample(0xc8201ede40, 0xc82020c4e0, 0x0, 0x0)
	CODEPATH/go/project/src/github.com/goadesign/goa/design/definitions.go:117 +0x4e
github.com/goadesign/goa/design.(*AttributeDefinition).finalizeExample(0xc8201ede40, 0xc820130960, 0x1, 0x1, 0x0, 0x0, 0x0)
	CODEPATH/go/project/src/github.com/goadesign/goa/design/definitions.go:198 +0x23f
github.com/goadesign/goa/design.(*AttributeDefinition).finalizeExample(0xc82019a2c0, 0xc820130960, 0x1, 0x1, 0x0, 0x0, 0xc8201e3af0)
	CODEPATH/go/project/src/github.com/goadesign/goa/design/definitions.go:185 +0x927
github.com/goadesign/goa/design.(*UserTypeDefinition).Finalize(0xc820145100)
	CODEPATH/go/project/src/github.com/goadesign/goa/design/types.go:513 +0x62
github.com/goadesign/goa/dslengine.finalizeSet(0xc8202025a0, 0x6, 0x6, 0x0, 0x0)
	CODEPATH/go/project/src/github.com/goadesign/goa/dslengine/runner.go:249 +0x102
github.com/goadesign/goa/design.(*APIDefinition).IterateSets(0xc8201a4d80, 0xaa1380)
	/CODEPATH/go/project/src/github.com/goadesign/goa/design/api.go:499 +0x33c
github.com/goadesign/goa/dslengine.Run(0x0, 0x0)
	CODEPATH/go/project/src/github.com/goadesign/goa/dslengine/runner.go:81 +0x3ee
main.main()
	CODEPATH/go/goa/src/patest/goagen749525142/main.go:23 +0x27

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 21 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

```

It seems that 0 is used as denominator.

After deleting code `Minimum(0)` or instead by other number, it work.

**Comment by raphael** [comment]
Fixed, thank you!
