### ISSUE TITLE
Error: unknown primitive type

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#260]
```go
var DataArray = MediaType("application/Array+json", func() {
	TypeName("DataArray")
	Attributes(func() {
		Attribute("items", Any, "item list")
	})

	View("default", func() {
		Attribute("items")
	})
})
```

In new version, it creates error by using type `Any`, error information:

```
$ goagen bootstrap -d patest/design

exit status 2
panic: unknown primitive type

goroutine 1 [running]:
github.com/goadesign/goa/design.Primitive.GenerateExample(0x6, 0xc820208780, 0x0, 0x0)
	$GOPATH/go/project/src/github.com/goadesign/goa/design/types.go:277 +0x144
github.com/goadesign/goa/design.(*Primitive).GenerateExample(0xc8201731a0, 0xc820208780, 0x0, 0x0)
	<autogenerated>:161 +0xa5
github.com/goadesign/goa/design.(*AttributeDefinition).GenerateExample(0xc8200a5760, 0xc820208780, 0x0, 0x0)
	$GOPATH/go/project/src/github.com/goadesign/goa/design/definitions.go:120 +0xa7
github.com/goadesign/goa/design.(*AttributeDefinition).finalizeExample(0xc8200a5760, 0xc8200369d8, 0x1, 0x1, 0x0, 0x0, 0x0)
	$GOPATH/go/project/src/github.com/goadesign/goa/design/definitions.go:198 +0x23f
github.com/goadesign/goa/design.(*AttributeDefinition).finalizeExample(0xc8200a4dc0, 0xc8200369d8, 0x1, 0x1, 0x0, 0x0, 0xc8201cdaf0)
	$GOPATH/project/src/github.com/goadesign/goa/design/definitions.go:185 +0x927
github.com/goadesign/goa/design.(*UserTypeDefinition).Finalize(0xc82019e300)
	$GOPATH/project/src/github.com/goadesign/goa/design/types.go:513 +0x62
github.com/goadesign/goa/dslengine.finalizeSet(0xc8201795e0, 0xa, 0xa, 0x0, 0x0)
	$GOPATH/go/project/src/github.com/goadesign/goa/dslengine/runner.go:249 +0x102
github.com/goadesign/goa/design.(*APIDefinition).IterateSets(0xc8201946c0, 0xaa4980)
	$GOPATH/go/project/src/github.com/goadesign/goa/design/api.go:499 +0x33c
github.com/goadesign/goa/dslengine.Run(0x0, 0x0)
	$GOPATH/go/project/src/github.com/goadesign/goa/dslengine/runner.go:81 +0x3ee
main.main()
	$GOPATH/goa/src/patest/goagen374805741/main.go:23 +0x27

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 11 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

It seems that I can't use the `Any` type.

`goagen` is the latest updating.

**Comment by raphael** [comment]
Fixed, thank you!
