### ISSUE TITLE
Panics when using a MediaType definition inside a Type definition

### ISSUE THREAD

**Issue by faxal** [goadesign/goa#668]
```
exit status 2
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x8deba0, 0xc82000e110)
	/home/fazal/Packages/go15/src/runtime/panic.go:464 +0x3e6
github.com/goadesign/goa/design.(*MediaTypeDefinition).DefaultView(0xc8201c2680, 0x0, 0x0)
	/home/fazal/.go/src/github.com/goadesign/goa/design/types.go:773 +0x27c
github.com/goadesign/goa/design.(*AttributeDefinition).finalizeExampleRecursive(0xc8201d6b80, 0xc8201d84a0, 0xc8201aaf50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/fazal/.go/src/github.com/goadesign/goa/design/definitions.go:1025 +0x5f6
github.com/goadesign/goa/design.(*AttributeDefinition).finalizeExampleRecursive(0xc8201d6900, 0xc8201d84a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/fazal/.go/src/github.com/goadesign/goa/design/definitions.go:1047 +0x948
github.com/goadesign/goa/design.(*AttributeDefinition).finalizeExample(0xc8201d6900, 0x0, 0x0)
	/home/fazal/.go/src/github.com/goadesign/goa/design/definitions.go:981 +0x58
github.com/goadesign/goa/design.(*UserTypeDefinition).Finalize(0xc8200bff40)
	/home/fazal/.go/src/github.com/goadesign/goa/design/types.go:670 +0x51
github.com/goadesign/goa/design.(*MediaTypeDefinition).Finalize(0xc8201c2600)
	/home/fazal/.go/src/github.com/goadesign/goa/design/types.go:712 +0x55
github.com/goadesign/goa/dslengine.finalizeSet(0xc8201d8440, 0x2, 0x2, 0x0, 0x0)
	/home/fazal/.go/src/github.com/goadesign/goa/dslengine/runner.go:328 +0x102
github.com/goadesign/goa/design.(*APIDefinition).IterateSets(0xc820196420, 0xa87220)
	/home/fazal/.go/src/github.com/goadesign/goa/design/definitions.go:474 +0x290
github.com/goadesign/goa/dslengine.Run(0x0, 0x0)
	/home/fazal/.go/src/github.com/goadesign/goa/dslengine/runner.go:114 +0x45c
main.main()
	/home/fazal/Dropbox/code/go/src/git.local/mec/goatest/goagen271720360/main.go:26 +0x7b
```

Reproducible with below design
```
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var TeamMemberPayload = Type("MemberPayload", func() {
	Description("A member")
	Attribute("id", String, "ID of member")
})

var TeamMember = MediaType("application/vnd.member+json", func() {
	TypeName("Member")
	Reference(TeamMemberPayload)
	Attributes(func() {
		Attribute("id")
	})

	View("default", func() {
		Attribute("id", String)
	})
})

var CasePayload = Type("CasePayload", func() {
	Attribute("owner", TeamMember, "Owner")
})

var Case = MediaType("application/vnd.case+json", func() {
	TypeName("Case")
	Reference(CasePayload)
	Attributes(func() {
		Attribute("id", String)
		Attribute("owner")
	})

	View("default", func() {
		Attribute("id")
	})
})
```

**Comment by raphael** [comment]
This is fixed both in master and v1, thanks!
