### ISSUE TITLE
Panic on goagen bootstrap

### ISSUE THREAD

**Issue by sachinbhutani** [goadesign/goa#707]
Get a panic with goagen bootstrap on my design. 
on Go 1.6 on Mac OSX 10.11

Commenting the last two Response statements causes the panic. 

Error: 
```
goagen bootstrap -d attest/design
exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xd098a]

goroutine 1 [running]:
panic(0x4e9780, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/goadesign/goa/design.(*MediaTypeDefinition).IsPrimitive(0x0, 0xc820210500)
	<autogenerated>:115 +0xa
github.com/goadesign/goa/design.(*AttributeDefinition).Validate(0xc8201c6380, 0xc820173c20, 0x11, 0xe44670, 0xc820172ce0, 0xc8202105a0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/design/validation.go:431 +0x1ed
github.com/goadesign/goa/design.(*AttributeDefinition).Validate(0xc8201c6080, 0xc8202105a0, 0xe, 0xe44670, 0xc820172ce0, 0x0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/design/validation.go:459 +0xa7b
github.com/goadesign/goa/design.(*UserTypeDefinition).Validate(0xc820172ce0, 0x0, 0x0, 0xe44228, 0xc82017ac60, 0x0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/design/validation.go:500 +0x278
github.com/goadesign/goa/design.(*APIDefinition).Validate.func3(0xc820172ce0, 0x0, 0x0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/design/validation.go:148 +0x8b
github.com/goadesign/goa/design.(*APIDefinition).IterateUserTypes(0xc82017ac60, 0xc8201f97a8, 0x0, 0x0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/design/definitions.go:543 +0x26e
github.com/goadesign/goa/design.(*APIDefinition).Validate(0xc82017ac60, 0x0, 0x0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/design/validation.go:150 +0x4cf
github.com/goadesign/goa/dslengine.validateSet(0xc82015fdd0, 0x1, 0x1, 0x0, 0x0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/dslengine/runner.go:312 +0x160
github.com/goadesign/goa/design.(*APIDefinition).IterateSets(0xc82017ac60, 0x692f10)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/design/definitions.go:454 +0xde
github.com/goadesign/goa/dslengine.Run(0x0, 0x0)
	/Users/sachin/sites/attest/src/github.com/goadesign/goa/dslengine/runner.go:108 +0x347
main.main()
	/Users/sachin/sites/attest/src/goagen177380650/main.go:26 +0x7b
```

Design Specification Causing panic 
commenting the last two Response statements causes panic

```
var User = MediaType("application/vnd.user", func() {
    Description("Attest User")
    Attribute("id",UUID, func(){
      Description("Unique User ID")
    })
    Attribute("firstName", String, func(){
      Description("First Name")
      Example("Sherlock")
      MinLength(1)
      MaxLength(50)
    })
    Attribute("lastName", String, func(){
      Description("Last Name")
      Example("Holmes")
      MinLength(1)
      MaxLength(50)
    })                 // Simple string attribute
    Attribute("email", String, func(){
      Description("Email")
      Format("email")
      Example("sherlock@example.com")
      MinLength(1)
      MaxLength(100)
    })
    Attribute("password", String, func(){
      Description("Passwod")
      MinLength(6)
      MaxLength(25)
    })
    Attribute("avatar", String, "Avatar")
    Attribute("data", HashOf(String, String))
    Attribute("created_at", DateTime, "Date of creation")
    // Attribute("created_by", User, "Created By")
    Attribute("updated_at", DateTime, "Date of last change")
    // Attribute("updated_by", User, "Changed By")

    Required("id", "firstName", "lastName","email", "created_at")

    View("default", func() {
      Attribute("id")
      Attribute("avatar")
      Attribute("firstName")
      Attribute("lastName")
      Attribute("email")
    })

    View("created", func(){
      Attribute("id")
      Attribute("avatar")
      Attribute("firstName")
      Attribute("lastName")
      Attribute("created_at")
      Attribute("data")
    })
})


var _ = Resource("user", func() {

	DefaultMedia(User)
	BasePath("/users")

	Action("list", func() {
		Routing(
			GET(""),
		)
		Description("Retrieve all users.")
		Response(OK, CollectionOf(User))
		Response(NotFound)
	})

	Action("show", func() {
		Routing(
			GET("/:userID"),
		)
		Description("Retrieve a user with given id.")
		Params(func() {
			Param("userID", UUID, "User ID")
		})
		Response(OK)
		Response(NotFound)
		Response(BadRequest, ErrorMedia)
	})

	Action("create", func() {
		Routing(
			POST(""),
		)
		Description("Create new user")
		Payload(func() {
			Member("firstName")
			Required("firstName")
		})
    Response(OK)
    //## commenting the below lines causes panic 
    // Response(Created, "/users/[0-9]+")
		// Response(BadRequest, ErrorMedia)
	})
})
```

**Comment by raphael** [comment]
I'm not able to repro with the design above latest - can you update and try again? thanks!

**Comment by sachinbhutani** [comment]
It's working fine now, thanks for your time. 
not able to re-create.
