### ISSUE TITLE
Code based generation seems to be broken

### ISSUE THREAD

**Issue by ottogiron** [goadesign/goa#986]
Hi,  I've been using code based generation for a while,  but a change in "goagen/gen_app/generator.go" has broken this option.

When runnig ***go run gen/main.go*** I get:

```
swagger/swagger.json
swagger/swagger.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9e136]

goroutine 1 [running]:
panic(0x406780, 0xc42000c1f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
goa-cellar/vendor/github.com/goadesign/goa/goagen/codegen.(*Validator).recurse(0x0, 0xc420233280, 0xc420000001, 0x47430c, 0x1, 0xc4202d069a, 0x6, 0x2, 0xc4202d0600, 0x6)
        /Users/ogiron/go/src/goa-cellar/vendor/github.com/goadesign/goa/goagen/codegen/validation.go:102 +0xf26
goa-cellar/vendor/github.com/goadesign/goa/goagen/codegen.(*Validator).Code(0x0, 0xc420233280, 0x1, 0x47430c, 0x1, 0xc4202d069a, 0x6, 0x2, 0x0, 0x0, ...)
        /Users/ogiron/go/src/goa-cellar/vendor/github.com/goadesign/goa/goagen/codegen/validation.go:89 +0x9e
goa-cellar/vendor/github.com/goadesign/goa/goagen/codegen.(*Validator).recurse(0x0, 0xc420233300, 0xc420000000, 0x47e52f, 0x7, 0x474b0b, 0x3, 0x1, 0xc420255600, 0xc4203de000)
```

A test using cellar and vendoring goa with glide: 

***glide.lock***

```
name: github.com/goadesign/goa
 version: 7fc6b55040a7f8a800500c44c547692a0d7aed77
```

```go 
package main

import (
	_ "goa-cellar/design"

	"github.com/goadesign/goa/design"
	"github.com/goadesign/goa/goagen/codegen"
	genapp "github.com/goadesign/goa/goagen/gen_app"
	genclient "github.com/goadesign/goa/goagen/gen_client"
	"github.com/goadesign/goa/goagen/gen_js"
	genmain "github.com/goadesign/goa/goagen/gen_main"
	genswagger "github.com/goadesign/goa/goagen/gen_swagger"
)

func main() {
	codegen.ParseDSL()
	codegen.Run(
		&genmain.Generator{
			API:    design.Design,
			Target: "app",
		},
		&genswagger.Generator{
			API: design.Design,
		},
		&genapp.Generator{
			API:    design.Design,
			OutDir: "app",
			Target: "app",
		},
		&genclient.Generator{
			API: design.Design,
		},
		// &genschema.Generator{
		// 	API: design.Design,
		// },
		&genjs.Generator{
			API: design.Design,
		},
	)
}
```

Check the comparison between the commit that used to work for me and master  for that file https://github.com/goadesign/goa/compare/4c757d240f48d44c0bf2afedfd31770f76e27ae4...master

It's seems to be related with the addition of

```go
validator *codegen.Validator    // Validation code generator
```

The only place in which the generator is being initialized is here:

goagen/gen_app/generator.go

```go
// Generate is the generator entry point called by the meta generator.
func Generate() (files []string, err error) {
	var (
		outDir, target, ver string
		notest              bool
	)

	set := flag.NewFlagSet("app", flag.PanicOnError)
	set.String("design", "", "")
	set.StringVar(&outDir, "out", "", "")
	set.StringVar(&target, "pkg", "app", "")
	set.StringVar(&ver, "version", "", "")
	set.BoolVar(&notest, "notest", false, "")
	set.Bool("force", false, "")
	set.Parse(os.Args[1:])
	outDir = filepath.Join(outDir, target)

	if err := codegen.CheckVersion(ver); err != nil {
		return nil, err
	}

	target = codegen.Goify(target, false)
	g := &Generator{OutDir: outDir, Target: target, NoTest: notest, API: design.Design, validator: codegen.NewValidator()}

	return g.Generate()
}
```

So when codegen.Run calls generator.Generate on my example given the fact I can't initialize the validator it gets that nil exception. 

Adding this (even I know is not the correct solution), makes the boostraping succeed 

```go
// Generate the application code, implement codegen.Generator.
func (g *Generator) Generate() (_ []string, err error) {
	g.validator = codegen.NewValidator()
          ...
```

Maybe a constructor function would be a better option for initializing generators so details such those can be addressed easily.

Thank you,

Otto.

**Comment by raphael** [comment]
Thank you for the detailed report. I agree with your analysis and conclusion that a constructor method would work well. Would you care doing the honors? :)

**Comment by ottogiron** [comment]
@raphael I would be glad. I'll take some time to work on something this week and I'll get back to you.
